name: Build and Deploy Vite React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./react/sample-temp

      - name: Build the App
        run: npm run build
        working-directory: ./react/sample-temp

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: react/sample-temp/dist
